using System.Collections.Generic;

namespace Scalpel.Services
{
    /// <summary>
    /// Consumer-facing release notes shown in the "What's New" popup, newest first.
    /// Plain data — edit this list to add a release (keep entries short and user-friendly).
    /// </summary>
    public static class Changelog
    {
        public sealed record Release(string Version, string Date, string[] Changes);

        public static IReadOnlyList<Release> Releases { get; } = new[]
        {
            new Release("2.2.0", "September 2026", new[]
            {
                "Save As on a new document now starts in the folder you last opened a PDF from.",
                "Fixed: closing a confirmation or save prompt with Alt+F4 or from the taskbar counted as answering OK. It now counts as Cancel, as in any Windows message box, so it no longer runs a redaction, removes metadata, or discards unsaved changes.",
                "Copying OCR text or a tab's path no longer fails or silently does nothing when another program is using the clipboard.",
                "Scalpel reopens the tabs you had open. The tab you were on loads right away; the rest reload the moment you click their tab.",
                "Each open PDF now keeps its own tab, with its own unsaved changes, undo history, and the page, zoom, layout and scroll position you left it at - opening another file, or switching tabs, no longer discards your work or loses your place. Closing a tab, or closing Scalpel while tabs are still unsaved, asks about every document that has changes to save.",
                "New tab bar under the ribbon: drag tabs to reorder, middle-click to close, right-click for Close other tabs, Close tabs to the right, Open containing folder and Copy path. A dot marks a tab with unsaved changes, + (Ctrl+T) opens a new tab, and with many tabs open a list button shows them all. Ctrl+1 to Ctrl+8 go to that tab and Ctrl+9 to the last one; fit width and fit page moved to Ctrl+Shift+2 and Ctrl+Shift+3.",
                "Working with many tabs now uses less memory: closing a tab deletes its own temporary files right away instead of waiting for Scalpel to exit, background tabs release their page images until you switch back to them, and undo history is capped across all open tabs together rather than per tab.",
                "Fixed: after opening another file, the page list in the sidebar could briefly show the previous document's pages.",
                "Fixed: Scalpel could close with no warning while loading page thumbnails, most often on longer documents. The page-drawing library kept a pointer to a block of memory that could be moved while it was still in use; that block is now held in place for as long as the document is open.",
                "Fixed: editing text only covered the original words, it did not remove them. The old text stayed inside the file, so selecting, searching or copying from the saved PDF still returned it alongside the replacement - anyone editing a name, an address or a figure had not actually changed it. The original run is now taken out of the page. Where it cannot be identified with certainty the text is left in place rather than risking damage to the page, and that is recorded in the diagnostic log.",
                "Exported grayscale pages are now stored with a single shade per pixel instead of three identical colour channels, and black-and-white pages with one bit per pixel. A scanned page exported in black and white is dramatically smaller, which is the reason for choosing it. Images that genuinely contain transparency keep their full colour format so nothing is lost.",
                "New Tools > Export pages as images: writes the pages you have selected (or all of them) out as PNG or JPEG, one file per page, at 72 to 600 DPI. Scanned pages can be exported in grayscale or hard black and white for a fax or a photocopier without needing an image editor.",
                "New Tools > Compare with another PDF: checks this document against another page by page and reports which pages differ, how much of each page changed, and in how many places. For answering \"is this the same contract I signed?\" without opening two windows side by side.",
                "New Tools > Measure distance: drag across the page to read a distance in millimetres, inches and points. Hold Shift to keep the line straight. The reading depends only on the page, so it is the same whatever your zoom level.",
                "New Tools > Straighten photographed page: mark the four corners of the page in a photo and the perspective is undone, turning a phone snap of a document into something square enough to read, print and run OCR on.",
                "New Tools > Fill form fields by OCR: reads what is printed or written inside each fillable box on the page and puts it into that field. For a form that was filled in on paper and scanned back over the original template, where the boxes are still empty and the answers only exist as pixels. Each box is read on its own, and the field's own rules (a maximum length, a list of allowed choices) are used to clean up the result.",
                "Comb form fields - the ones printed as a row of little boxes, one character each, for an ID number or a date - are now shown and filled the way they are printed, one character per box, instead of as a single run of text crammed to the left. They are also written that way into the saved file, so they look right in other PDF readers too.",
                "Fixed: cropping a page that was turned upside down kept the wrong half of it. Selecting the top of what you saw cropped to the bottom of the page instead. Crop now matches what is on screen at every rotation.",
                "Fixed: copying text from a document laid out in columns interleaved the columns line by line, which made the result unusable. Text is now copied one whole column at a time, and each line follows its own direction so Hebrew and Arabic come out in reading order.",
                "Ctrl+B, Ctrl+I and Ctrl+U now make the text you are typing bold, italic or underlined, and the styling is kept when the text is saved into the PDF.",
                "Pinch to zoom now works on a touchscreen or precision touchpad, and a two-finger drag pans the page.",
                "Fixed: zoom shortcuts did nothing on keyboards where those characters need Shift - German, French, Nordic and others. Zoom in, zoom out and the shortcut help are now matched by the character your keyboard actually types, and the help screen prints the keys your layout really uses.",
                "Fixed: saving with a name that already contained a dot - \"contract.final\", say - produced a file Windows did not treat as a PDF, so it would not reopen by double-clicking. The .pdf ending is now always added. Password-protected and digitally signed copies were affected the same way.",
                "Fixed: undo history could grow without limit. A single page operation on a large scanned document stores a whole copy of it, so a long editing session could consume hundreds of megabytes. History is now capped by both size and depth, and the most recent step is always kept.",
                "Fixed: zooming quickly with the wheel or a pinch could leave the page scrolled to where an earlier step wanted it, because a stale scroll adjustment landed after a newer one.",
                "Clicking a printed dotted or ruled blank with the text tool now places the text box on the line, sized to it, instead of wherever the click landed. For filling in a form that was flattened to a plain page.",
                "Saved PDFs no longer claim to have been produced by the PDF library Scalpel uses, and no longer carry a transparency group that Scalpel never asked for. The group is a PDF/A conformance failure and could make a page print differently from how it was shown.",
                "About now shows the date this version was released, not just its number.",
                "Fixed: a rare crash that could close Scalpel with no warning while pages were being drawn. All page rendering is now done on a single dedicated thread, which is what the underlying rendering library requires.",
                "Translators can now run Scalpel against a translation file on disk with --lang-file, and see every string in place without needing a rebuild. Anything the file does not translate falls back to English.",
                "Fixed a rare crash that closed Scalpel with no warning and nothing in the log. Page rendering is handled by a library that can only do one thing at a time, but Scalpel was drawing sidebar thumbnails, background pages and the page you are looking at all at once. Rendering is now serialized, which also makes large documents behave more predictably.",
                "Annotations that a PDF already carries - highlights, sticky notes, stamps, drawings added in another program - are now shown on the page instead of being invisible, and they are no longer silently dropped from Print, Save Flattened and page thumbnails.",
                "New Tools > Comments: read and edit the notes reviewers left in a PDF. Pick a comment to read it in full, correct its text, change who it is attributed to, or remove one that has been dealt with - without opening another PDF reader. Nothing is written until you choose Save changes, and the edit can be undone like any other.",
                "New Tools > Preflight check: reviews the open document for the things that go wrong once it leaves your machine - pages other readers refuse, images that will print blurry, fonts the recipient does not have, forms that are still editable - and reports what it finds.",
                "Fixed: cropping a page that was turned upside down kept the wrong half of it. Selecting the top of what you saw cropped to the bottom of the page instead. Crop now matches what is on screen at every rotation.",
                "Fixed: rotating a page threw away every unsaved annotation on it. Annotations are now kept and turned with the page, and anything near an edge is kept inside the new page bounds.",
                "Fixed: annotations, signatures and stamps were burned into the wrong place when a page had been rotated - they came out turned, offset and stretched on swapped axes. Text, drawings and images now save exactly where you put them on a rotated page.",
                "Updated the image-handling library to clear seven published security advisories affecting how untrusted images inside a PDF are decoded.",
                "New Redo: Ctrl+Y or Ctrl+Shift+Z re-applies what you just undid, for annotations and for document changes alike, with a Redo button beside Undo. Starting a new edit clears the redo chain.",
                "Fixed: the right-hand page in Two-Page view rendered softer than the left one, and continuous scroll rendered at a fixed 2x regardless of your display, wasting memory on a standard screen and still looking soft on a high-DPI one. Both now render at your display's real resolution.",
                "Fixed: a selection box or drawing preview could be left stranded on a page and stay there until Scalpel was restarted. Overlays are now removed from the page that actually holds them.",
                "New \"Remove password\" in the Save menu: a PDF that needed a password can now be saved back without its protection as a deliberate action. Scalpel already had to decrypt such a file to work on it, so an ordinary Save now says plainly that the protection was dropped instead of doing it silently.",
                "OCR to clipboard now recognises every page you have selected in the Pages panel and copies the combined text, with page-by-page progress.",
                "OCR gained Bengali, Turkish, Czech, Hungarian, Kazakh and Polish, so every language Scalpel's interface ships in now has a matching recognition model.",
                "Shift+scroll now scrolls a zoomed page sideways, a tilt wheel or two-finger sideways swipe works in the document, and scrolling honours the lines-per-notch setting from Windows Mouse Properties.",
                "New privacy setting: \"Don't remember recently opened files\" in Settings. Turning it on also clears the list that is already there.",
                "Image, signature, stamp and certificate pickers each remember their own last folder instead of opening wherever the last PDF came from.",
                "Fixed: the search bar's messages (no matches, the result count, errors and the close button tip) were always in English; they are now translated.",
                "Fixed: opening another document while a large one was still drawing could paint stray pages from the old file into the new one.",
                "Fixed: an error that repeats on every redraw no longer stacks up crash dialogs; one appears, once the app is idle.",
                "Fixed: filling in a PDF form on a computer that uses a comma as the decimal separator (German, French, Spanish, Italian, Turkish, Russian and others) wrote a damaged appearance into the file, so the values you typed came out blank or garbled in other PDF readers and in print.",
                "Fixed: \"Save Flattened\" and Print silently dropped the values typed into form fields - the output came out with empty fields.",
                "Fixed: a multi-line form field is now written as real lines instead of one long run, and text keeps smart quotes, dashes and the euro sign instead of turning them into question marks.",
                "Fixed: every keyboard shortcut stopped working while a form field or text box had focus. Ctrl+S, Ctrl+P, Ctrl+F, Ctrl+O, Ctrl+Tab and the function keys now keep working, while ordinary typing and text-editing keys stay inside the field.",
                "Fixed: full screen no longer stays on top of every other program when you switch away from Scalpel.",
                "Links inside a PDF now open only web and email addresses. A document can no longer use a link to start a program or open a file on your computer, and a plain address like www.example.com now opens correctly.",
                "Fixed: clicking a page in continuous scroll no longer yanks that page to the top of the view.",
                "Fixed: a background error no longer pops up a crash report you cannot act on; it is still written to the diagnostic log.",
                "Fixed: opening a PDF whose page list is empty or damaged no longer crashes the viewer.",
                "Every save now repairs the document on the way out: a leftover empty bookmark entry, a zero-size crop box that made Acrobat refuse the file, and signature data that an edit has invalidated are all cleaned up, and the signature field itself is kept so the file can be signed again.",
                "Fixed: a signature, stamp or image placed on top of a form field is no longer hidden behind it.",
                "Fixed: printing a page range like 1-999999 froze the app, and a range matching no pages printed the whole document instead. Print is now simply unavailable until the range matches something.",
                "Print can now do odd pages only or even pages only, so you can print one side, flip the stack and print the other on a printer with no duplexer.",
                "Print has a grayscale option, and the two-sided choice is now sent to the printer explicitly, so turning it off is no longer overridden by the printer driver default.",
                "Fixed: flattened and printed pages no longer carry a see-through background, which made some exports come out black.",
                "New shortcuts: Home and End jump to the first and last page, Ctrl+0 is actual size (a true 100% in every view mode), Ctrl+Shift+2 fits the width, Ctrl+Shift+3 fits the page, Shift+F4 shows the file size, F3 and Shift+F3 step through search results, Ctrl+Shift+W closes the other tabs, and the number keys pick tools.",
                "Document Info now opens with F4 or Ctrl+D, and F12 opens About, matching the usual PDF viewer convention.",
                "Esc now steps down instead of straight out: it cancels what you are doing, then returns to the Select tool, and only closes Scalpel after that.",
                "Ctrl+scroll zooming is now a steady 10% per notch, so zooming in and back out returns to where you started, and precision touchpads glide smoothly instead of jumping.",
                "Fixed: scrolling quickly to the bottom of a page no longer skips several pages at once; changing page at the edge now takes a deliberate scroll.",
                "Fixed: editing existing text set in Helvetica, Courier, Times or Symbol kept the right typeface instead of falling back to the interface font.",
                "Enter and Esc now confirm and cancel Scalpel dialogs, and prompts that can discard your work default to No.",
                "Fixed: page numbers in the sidebar, the outline and page tooltips are now translated instead of always showing English.",
                "Fixed: one damaged annotation could abort a whole save; it is now skipped and recorded in the log so the rest of your work is still written.",
                "Fixed: a saved signature with a broken stored size could crash the page it was placed on.",
                "Fillable text fields now show a text cursor whichever tool is active, so it is clear they can be typed into.",
                "Fixed: scrolling a zoomed-in page no longer jumps to the next page when you reach its bottom edge (or back to the previous one when you scroll up). The mouse wheel now just scrolls within the page; it only flips pages when the whole page fits on screen.",
                "Fixed: saving a PDF that has no bookmarks could produce a file Scalpel itself then refused to open (\"damaged structure\" prompt) or re-save (\"Save failed: Unexpected token 'xref'\" right after a successful save). Files already saved that way now open normally for editing, and new saves no longer have the defect.",
                "Fixed: opening a second PDF (double-click in Explorer, or the Store tile) while Scalpel was already running could break the first window with a \"could not open file\" error - the new launch deleted the other window's working copy of a protected or repaired document. Working copies are now tied to the window that owns them and only cleaned up once it has closed.",
                "Scalpel now runs as a single window: double-clicking another PDF opens it as a new tab in the window you already have (and brings it to the front) instead of starting a second copy of the app. \"Edit with Scalpel PDF\" still lands you straight in Edit mode.",
                "Open several PDFs at once from the Open dialog, by dragging them in, or from Explorer; each gets its own tab.",
                "Diagnostic logs are now kept for 90 days (up to 200 sessions) instead of 7, so a problem you noticed a few weeks ago can still be looked into from Settings > Diagnostics.",
                "The log now records every error or warning dialog Scalpel shows - including exactly why a PDF could not be opened, why a file repair failed, and why saved signatures could not be read or written - so bug reports can be traced instead of guessed at.",
            }),
            new Release("2.1.0", "July 2026", new[]
            {
                "New OCR Region tool (Tools ▸ OCR Region): drag a rectangle over any part of a page to copy just that area's text to the clipboard — handy for grabbing a single paragraph, table cell, or caption from a scan.",
                "Digitally Sign can now use a certificate already installed in Windows — pick \"Windows certificate store\" and choose from a list (smart cards and enterprise-issued certificates included), instead of locating a .pfx/.p12 file and typing its password.",
                "Digitally Sign can optionally add a trusted RFC-3161 timestamp, so the signature proves *when* it was made and stays valid even after your certificate expires. Tick \"Add a trusted timestamp\" when signing (it contacts a timestamp authority over the internet).",
                "Digitally Sign can now show a visible signature on the first page — a small captioned box (signer name, date, and an optional reason) placed in the corner you choose, instead of an invisible signature. Pick a corner under \"Visible signature\" when signing.",
                "Digitally Sign can optionally embed long-term validation (LTV) info — the certificate chain plus any reachable revocation lists — into the signed PDF, so it can still be validated years later. Tick \"Embed long-term validation info\" (best paired with a trusted timestamp and a CA-issued certificate).",
            }),
            new Release("2.0.0", "June 2026", new[]
            {
                "Make Searchable (OCR) now shows live progress (\"Recognizing page X of Y\") and can be cancelled with the button or Esc, so long scans no longer leave you waiting with no feedback.",
                "The saved-signatures chooser now drops down directly beneath the Sign button and follows your theme (it used to float in the page and stay dark in Light mode); clicking away closes it cleanly.",
                "New Digitally Sign tool (Tools menu): add a real, invisible cryptographic signature to a PDF using your own certificate (.pfx/.p12). Scalpel appends the signature without re-writing the rest of the file, so the signed copy stays valid in PDF readers — all on your machine, no online service.",
                "Document tabs: open several PDFs and switch between them from a tab strip above the page — click a tab, press Ctrl+Tab to cycle, or close one with its ×. Switching prompts you to save any unsaved changes first. The strip stays hidden until you have more than one file open.",
                "Form fields are now positioned correctly on cropped PDFs and appear in every view mode — including the continuous scroll, two-page, and grid views, not just single-page view.",
                "New Transform Pages tool (Tools menu): rotate pages in 90° steps, fine-deskew by a small angle, scale up or down, and flip horizontally or vertically — over the whole document or a page range. A plain 90° rotation stays crisp and text-selectable; deskew, scale, and flip re-render the affected pages as images.",
                "New Watermark / Stamp tool (Tools menu): add a semi-transparent text watermark like \"CONFIDENTIAL\" — diagonal, tiled, or pinned to any corner — and optionally stamp an image or logo, with adjustable opacity, size, rotation, and a page range.",
                "New color picker for the Draw, Line, and Text tools: click the \"+\" next to the swatches to choose any color with an RGB/hex picker, or use the eyedropper to grab a color from anywhere on your screen.",
                "Recent files: reopen a recently-opened PDF from the start screen or by right-clicking the Open button; missing files clean themselves out of the list.",
                "OCR upgrades: pick from many languages and a high-quality mode, copy a page's recognized text to the clipboard, or extract all text to a .txt/.md file — all on your machine.",
                "New full-screen mode (F11) plus keyboard shortcuts: F1 shortcuts, F2 about, F5–F8 view modes, and letter keys (V/T/H/D/L/I) to pick Edit tools.",
                "New Document Info (Tools menu or F12): view and edit a PDF's title, author, subject, keywords, and creator, with a read-only summary of producer, page count, version, date, and size.",
                "New Line tool in the Edit tab: drag to draw a straight line, and hold Shift to snap it to horizontal, vertical, or 45°. It uses the same color, width, and opacity as the Draw tool.",
                "Fixed: editing existing Hebrew (and other right-to-left) text now keeps the words in their correct order — a line with more than one Hebrew word used to come back reversed in the edit box.",
                "Hebrew and Arabic edit boxes now read and align right-to-left while you type, so editing existing text feels natural.",
                "Editing existing text now matches the original font: if that font isn't installed, Scalpel uses the document's own embedded font when it can, and otherwise tells you exactly which font to install and uses a close substitute in the meantime — for any language.",
                "Fixed: Redact now works on PDFs with damaged or unusual internal structure that previously failed with an \"Unexpected token 'xref'\" error — such files are now safely flattened and redacted instead.",
                "Fixed: OCR (Make Searchable) now actually produces searchable text. Previously the recognized text could be silently dropped, leaving the saved PDF non-searchable; the page text is now selectable and searchable as intended.",
                "The Tools operations (Redact, Compress, Make Searchable) are also more robust: if something goes wrong they now show a clear message instead of closing the app.",
                "Compress now explains it works best on scanned or photo-heavy PDFs (mostly-text files may not shrink), and reuses an already-installed Tesseract for OCR instead of re-downloading language data.",
            }),
            new Release("1.8.0", "June 2026", new[]
            {
                "Optional update notifications: Scalpel can now let you know when a new version is out. It's off until you turn it on, sends no information about you or your files, and you can toggle it anytime in Settings.",
                "The notification links you straight to the right place to update — the Microsoft Store for Store installs, the website for portable and installed copies.",
                "Fixed: the Settings checkboxes are now clearly legible in Dark and High Contrast themes.",
            }),
            new Release("1.7.0", "June 2026", new[]
            {
                "Brand-new ribbon interface: the toolbar is now organized like familiar office apps — the View, Edit, Pages, and Sign tabs open clearly labeled groups of tools.",
                "A Quick Access toolbar in the title bar keeps Open, Save, Print, and Undo one click away from anywhere.",
                "Refreshed look: a clean, clinical light theme with a precise red accent is now the default, with a smooth animated transition when you switch tabs.",
                "Zoom moved to the bottom-right of the status bar, where you'd expect it.",
                "The new design carries across every theme — Light, Dark, and High Contrast — and all accent colors.",
                "Refreshed app icon and Store artwork to match — a steel tile with the scalpel's surgical-red cutting edge.",
            }),
            new Release("1.6.0", "June 2026", new[]
            {
                "New Tools menu with five local-only power features — no subscription, no uploads.",
                "Page numbering, Bates numbering, and custom headers/footers you can place in any corner.",
                "Compress PDF: shrink scan- and photo-heavy files with Low/Medium/High presets, all on your machine.",
                "Make Searchable (OCR): turn scanned pages into selectable, searchable text offline (one-time local language-data download).",
                "Password protect: encrypt a copy with a password and printing/copying permissions.",
                "Remove metadata: strip author, title, and hidden data before sharing.",
            }),
            new Release("1.5.1", "June 2026", new[]
            {
                "Added Hebrew, Arabic, and Russian — including a full right-to-left interface for Hebrew and Arabic.",
                "You can now type and edit Hebrew, Arabic, and Russian text directly on your PDFs; letters shape and read in the correct order.",
                "Settings now group Theme, Accent, and Language into collapsible sections for a tidier panel.",
                "Added a “What's New” button (next to About) with release notes organized by version.",
                "The toolbar and Settings panel scroll on small screens, so nothing gets cut off.",
                "Fixed: editing text while using a right-to-left interface now places the edit box over the correct spot.",
                "Fixed: the text edit box now matches the size of the text you're editing, including large headings.",
            }),
            new Release("1.5.0", "June 2026", new[]
            {
                "New “Studio” interface: a cleaner toolbar organized into View, Edit, Pages, and Sign modes.",
                "Light, Dark, and High-Contrast themes, each with Amber, Red, Green, and Cyan accent colors.",
                "More interface languages: Spanish, Traditional and Simplified Chinese, Bengali, and Turkish.",
                "Faster, sharper page rendering and a refreshed page thumbnail sidebar.",
            }),
            new Release("1.4", "Earlier", new[]
            {
                "Core editing toolkit: add text, highlights, freehand ink, images, and signatures.",
                "Merge, split, extract, reorder, rotate, and crop pages.",
                "Fill in PDF forms, print, and save a flattened (uneditable) copy.",
                "Single portable app with no installer and no telemetry.",
            }),
        };
    }
}
